config/routes.rb
Mypeeps::Application.routes.draw do

	root to: "static_pages#home"
	get "updates/updates"
	get "updates/posts"
	get "updates/comments"
	
	resources :stream, only: :comments do
		get 'comments', on: :member
	end
	resources :members do
		get 'crop', on: :member
		get 'new_post', on: :member
	end
	resources :sessions, only: [ :new, :create, :destroy]
	resources :auth_api, only: [ :create, :destroy]
	resources :relationships, only: [ :create, :destroy]
	resources :spouse_relationships, only: [ :create, :destroy]
	resources :tree, only: [ :show, :edit, :update]
	resources :password_resets, only: [ :new, :create, :edit, :update] do
		member do
			get :change_password
			patch :update_password
		end
	end
	resources :comments, only: [ :create, :destroy]
	resources :posts, only: [ :show, :create, :edit, :update, :destroy] do
		member { get :partial }
	end
	
	get '/signup', to: 'members#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="center hero-unit"> 
	<h1>Welcome to my peeps!</h1> 

	<div id="my_peeps_description">a place to share your photos and videos with the family.</div>

	<br/>
	
	
	<div class="boxes">
		<% (1..4).each do |i| %>
			<% (1..4).each do |i| %>
				<div class="box"></div>
			<% end %>
			<br/>
		<% end %>
	</div>

	<br/>	
	<div id="fb">because what happens on facebook stays on facebook.</div>
	<br/>
	<%= link_to "Sign in now!", signin_path, class: "btn btn-lg btn-primary", id: "signin" %>
	<br/>
</div> 