config/routes.rb
Mypeeps::Application.routes.draw do

	root to: "static_pages#home"
	get "updates/updates"
	get "updates/posts"
	get "updates/comments"
	
	resources :stream, only: :comments do
		get 'comments', on: :member
	end
	resources :members do
		get 'crop', on: :member
		get 'new_post', on: :member
	end
	resources :sessions, only: [ :new, :create, :destroy]
	resources :auth_api, only: [ :create, :destroy]
	resources :relationships, only: [ :create, :destroy]
	resources :spouse_relationships, only: [ :create, :destroy]
	resources :tree, only: [ :show, :edit, :update]
	resources :password_resets, only: [ :new, :create, :edit, :update] do
		member do
			get :change_password
			patch :update_password
		end
	end
	resources :comments, only: [ :create, :destroy]
	resources :posts, only: [ :show, :create, :edit, :update, :destroy] do
		member { get :partial }
	end
	
	get '/signup', to: 'members#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include ActionView::Helpers::DateHelper

	after_create :create_update
	after_create :notify_members
	before_destroy :delete_update
	
	def notify_members
		from_whom = Member.find_by_id(member_id)
		comment = { comment: self, name: from_whom.first_name.downcase, sent_when: time_ago_in_words(self.created_at).to_s + ' ago', url: from_whom.image_url( :micro) }.to_json
		$redis.publish( "comments.create.#{to_member}", comment)
		logger.info "published to comments.create.#{to_member}"
	end
	
	def create_update
		post = Post.find_by_id( self.post_id)
		
		if post.comments.count > 1
			post.comments.select(:member_id).distinct.each do |commenter|
				member = Member.find_by_id( commenter.member_id)
				Update.where(member_id: member.id, update_on_type: 'post', update_on_id: post.id, from_member: self.member_id).each do |u|
					u.destroy
				end
				unless member.id == self.member_id || member.id == post.member_id
					update = member.updates.create!( from_member: self.member_id, update_on_type: 'post', update_on_id: post.id, updated_by_type: 'comment', updated_by_id: self.id)
				end
			end
			member_who_has_post = Member.find_by_id(post.member_id)
			Update.where(member_id: member_who_has_post.id, update_on_type: 'post', update_on_id: post.id, updated_by_type: 'comment', from_member: self.member_id).each do |u|
				u.destroy
			end
			member_who_has_post.updates.create!( from_member: self.member_id, update_on_type: 'post', update_on_id: post.id, updated_by_type: 'comment', updated_by_id: self.id) unless self.member_id == post.member_id
		else
			unless post.from_member == self.member_id
				member_who_posted = Member.find_by_id( post.from_member)
				member_who_posted.updates.create!( from_member: self.member_id, update_on_type: 'post', update_on_id: post.id, updated_by_type: 'comment', updated_by_id: self.id)
=begin
			Update.where(member_id: member_who_posted.id, update_on_type: 'post', update_on_id: post.id, from_member: self.member_id).each do |u|
				u.created_at = self.created_at
				u.save
			end
			Update.where(member_id: member_who_has_post, updated_by_type: 'post', updated_by_id: post.id, from_member: self.member_id).each do |u|
				u.created_at = self.created_at
				u.save
			end
=end
			end
			unless post.member_id == self.member_id
				member_who_has_post = Member.find_by_id(post.member_id)
				member_who_has_post.updates.create!( from_member: self.member_id, update_on_type: 'post', update_on_id: post.id, updated_by_type: 'comment', updated_by_id: self.id)
			end
		end
	end
	
	def delete_update
		Update.where( updated_by_type: 'comment', updated_by_id: self.id).each do |update|
			update.destroy
		end
	end
	
	private
		def to_member
			Post.find_by_id(self.post_id).member_id
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_filter :signed_in_filter
	before_filter :can_delete?, only: :destroy
	
	def create
		@comment = Comment.create( comment_params)
		@post_id = @comment.post_id.to_s
		@to_member = current_member.id.to_s
		@show_spacebar_hint = current_member.show_spacebar_hint
	end

	def destroy
		@comment_to_delete = Comment.find_by_id( params[ :id])
		@comment_to_delete.destroy
		respond_to do |format|
			format.js
			format.html { redirect_to image_path( @comment_to_delete.image_id) }
		end
	end
	
	private
	
		def comment_params
			params.require(:comment).permit(:post_id, :member_id, :member_name, :content)
		end
		
		def can_delete?
			comment = Comment.find_by_id( params[ :id])
			unless current_member.can_delete_comment?(comment) || current_member.admin?
				redirect_to :back, status: 303, error: "You do not have permissions to delete this comment."
			end
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="<%= comment.id %>", class="comment_block">
	<% member = Member.find_by_id(comment.member_id) %>
	<%= link_to image_tag( member.image_url(:micro), class: 'comment_member_image img-rounded'), member_path(member) %>
	<%= link_to member.first_name.downcase, member_path(member) %><%= ": #{comment.content}" %><br/>
	<%= "- " + time_ago_in_words(comment.created_at).to_s + " ago" %>
	<% if current_member.can_delete_comment?(comment) %>
		| <%= link_to "delete", comment_path(comment), method: :delete, remote: true %>
	<% end %>
	<br/>
</li>

app/views/comments/_comment_form.html.erb
<%= form_for( post.comments.new( member_id: current_member.id), html: {class: 'show_post_comment_form f-hz'}, remote: true) do |f| %>
	<%= f.hidden_field :post_id %>
	<%= f.hidden_field :member_id %>
	<%= f.text_field :content, placeholder: 'enter a comment...', autofocus: true %>
	<%= f.submit "post", class: "btn btn-xs btn-hz", id: "comment_submit" %>
<% end %>

app/views/comments/_comment_form_overlayed.html.erb
<%= form_for( post.comments.new( member_id: current_member.id), html: {class: 'show_member_comment_form'}, remote: true) do |f| %>
	<%= f.hidden_field :post_id %>
	<%= f.hidden_field :member_id %>
	<%= f.text_area :content, placeholder: 'enter a comment...', autofocus: true %>
	<%= f.submit "post", class: "btn btn-primary btn-sm btn-hz btn-within", id: "comment_submit" %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/create.js.erb
<% if @comment.new_record? %>
	alert("Failed to post comment: <%= j @comment.errors.full_messages.join(', ').html_safe %>");
<% else %>
	$('#image_comments').prepend("<%= j render @comment %>")
	$('#comment_content').val('')
	image_block = $('div.image_block#<%= j @post_id%>')
	console.log(image_block)
	<% if @show_spacebar_hint %>
		console.log('here i am')
		if(image_block.attr('data-type') == 'written'){
			comment_link = image_block.find('.comment_link')
			comment_link.qtip({
				content:{
					text: 'Press the spacebar key to continue this conversation. This will work anytime just after you have submitted a comment on a post.'
				},
				show:{
					ready: true
				},
				style:{
					classes: 'qtip-blue qtip-info'
				}
			})
			path = '/members/<%= j @to_member %>'
			id = '<%= j @to_member %>'
			$.ajax({
				type: "PATCH",
				url: path,
				data: { id: id, member: { 'show_spacebar_hint' : 'false' } }
			})
		}
	<% end %>

<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/destroy.js.erb
$('li#<%= @comment_to_delete.id %>').fadeOut(1000)