config/routes.rb
Mypeeps::Application.routes.draw do

	root to: "static_pages#home"
	get "updates/updates"
	get "updates/posts"
	get "updates/comments"
	
	resources :stream, only: :comments do
		get 'comments', on: :member
	end
	resources :members do
		get 'crop', on: :member
		get 'new_post', on: :member
	end
	resources :sessions, only: [ :new, :create, :destroy]
	resources :auth_api, only: [ :create, :destroy]
	resources :relationships, only: [ :create, :destroy]
	resources :spouse_relationships, only: [ :create, :destroy]
	resources :tree, only: [ :show, :edit, :update]
	resources :password_resets, only: [ :new, :create, :edit, :update] do
		member do
			get :change_password
			patch :update_password
		end
	end
	resources :comments, only: [ :create, :destroy]
	resources :posts, only: [ :show, :create, :edit, :update, :destroy] do
		member { get :partial }
	end
	
	get '/signup', to: 'members#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy'

end

app/models/update.rb
class Update < ActiveRecord::Base

	belongs_to :member
	belongs_to :updated_by, polymorphic: true

end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
	def posts
		if signed_in?
			@new_posts = []
			most_recent_post = params[ :most_recent_post].to_i + 2
			member = Member.find_by_id( params[ :member_id])
			member.updates.where( "updated_by_type= 'post' and created_at > ?", Time.at( most_recent_post)).each do |update|
				@new_posts << Post.find_by_id( update.updated_by_id)
			end
			@updates_count = current_member.updates.where("created_at > ?", current_member.last_checked_updates).count
		
			respond_to do |format|
				format.js
			end
		end
	end
	
	def comments
		post = Post.find_by_id( params[ :post_id])
		most_recent_comment = params[ :most_recent_comment].to_i + 1
		if signed_in?
			updates = current_member.updates.where( "update_on_type= 'post' and updated_by_type='comment' and update_on_id= ? and created_at > ?", post.id, Time.at( most_recent_comment))
			@new_comments = Comment.where( id: updates.select( :updated_by_id)).order('created_at DESC')

			respond_to do |format|
				format.js
			end
		end
	end
	
	def updates
		@updates = current_member.updates.order('created_at DESC')

		respond_to do |format|
			format.js
			format.html
		end
	end

end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_update.html.erb
<% distinct_updates = Update.find_by_sql("select updated_by_type, updated_by_id, max(created_at) as m from updates where member_id=#{current_member.id} group by updated_by_type, updated_by_id order by m desc") %>
<% distinct_updates.each do |distinct_group_of_updates| %>
	<li>
		<div class="update_block">
		<% names = [] %>
		<% link = 0 %>
		<% post = 1 %>
<!-- i could change this code so that i check the size of distinct_group_of_updates. if it's large than one, then iterate over that listed as i currently have below. otherwise, just run it. this avoids having to run subselects for every update. -->
		<% current_member.updates.where(updated_by_type: distinct_group_of_updates.updated_by_type, updated_by_id: distinct_group_of_updates.updated_by_id).order('created_at DESC').each_with_index do |update, index| %>
			<% member = Member.find_by_id( update.from_member) %>
			<% if index == 0 %>
				<%= image_tag member.image_url(:thumb) %>
				<% link = update.updated_by_id %>
			<% end %>
			<% names << member.first_name.downcase %>
		<% end %>
		<%= names.to_sentence %>
		<% if distinct_group_of_updates.updated_by_type == 'comment' %>
			<% comment = Comment.find_by_id( distinct_group_of_updates.updated_by_id) %>
			<% post = Post.find_by_id( comment.post_id ) %>			
		<% else %>		
			<% post = Post.find_by_id( distinct_group_of_updates.updated_by_id) %>
		<% end %>

		<% if distinct_group_of_updates.updated_by_type == 'comment' %>
			<% if post.image? %>
				<%= link_to "commented", post_path( post) %> on an image
			<% elsif post.video?%>
				<%= link_to "commented", post_path( post) %> on a video
			<% else %>
				<%= link_to "commented", member_path( post.member_id, anchor: post) %> on a post
			<% end %>
		<% elsif distinct_group_of_updates.updated_by_type == 'post' %>
			<% if post.image? %>
				posted an <%= link_to "image", post_path( post) %> to your profile page
			<% elsif post.video? %>
				posted a <%= link_to "video", post_path( post) %> to your profile page
			<% else %>
				<%= link_to "wrote", member_path( post.member_id, anchor: link) %> something on your profile page
			<% end %>
		<% end %>
		</div>
	</li>
<% end %>

app/views/updates/comments.js.erb
<% unless @new_comments.empty? %>
	$("#actual_image").attr('data-most-recent-comment', "<%= @new_comments.first.created_at.to_i %>")

	$('#image_comments').prepend( "<%= j render partial: 'comments/comment', collection: @new_comments, as: :comment %>" )
<% end %>

app/views/updates/posts.html.erb
<h1>Updates#posts</h1>
<p>Find me in app/views/updates/posts.html.erb</p>

app/views/updates/posts.js.erb
<% unless @new_posts.empty? %>
	$('#images').attr( 'data-most-recent-post', "<%= @new_posts.first.created_at.to_i %>")
	<% @new_posts.each do |post| %>
		new_post = $("<%= j render partial: 'posts/post', collection: @new_posts, as: :post %>")
		$("#member_info").after( new_post)
	<% end %>
<% end %>
<% if @updates_count == 0 %>
	$("div#updates_count").html("Up")
	$("div#updates_count").attr( 'class', 'no_updates')
<% else %>
	$("div#updates_count").html("+<%= j @updates_count.to_s %>")
	$("div#updates_count").attr( 'class', 'some_updates')
<% end %>

app/views/updates/updates.html.erb
<%= render @updates %>

app/views/updates/updates.js.erb
updates_count = $('div#updates_count')

<% if @updates.empty? %>
	updates_count.attr( 'data-updates', "<ul><li> No updates for you! </li></ul>")
<% else %>
	updates_count.attr( 'data-updates', "<ul><%= j render partial: 'update', object: @updates %></ul>")
<% end %>