config/routes.rb
Mypeeps::Application.routes.draw do

	root to: "static_pages#home"
	get "updates/updates"
	get "updates/posts"
	get "updates/comments"
	
	resources :stream, only: :comments do
		get 'comments', on: :member
	end
	resources :members do
		get 'crop', on: :member
		get 'new_post', on: :member
	end
	resources :sessions, only: [ :new, :create, :destroy]
	resources :auth_api, only: [ :create, :destroy]
	resources :relationships, only: [ :create, :destroy]
	resources :spouse_relationships, only: [ :create, :destroy]
	resources :tree, only: [ :show, :edit, :update]
	resources :password_resets, only: [ :new, :create, :edit, :update] do
		member do
			get :change_password
			patch :update_password
		end
	end
	resources :comments, only: [ :create, :destroy]
	resources :posts, only: [ :show, :create, :edit, :update, :destroy] do
		member { get :partial }
	end
	
	get '/signup', to: 'members#new'
	get '/signin', to: 'sessions#new'
	delete '/signout', to: 'sessions#destroy'

end

app/models/member.rb
include MembersHelper

class Member < ActiveRecord::Base
	include ActiveModel::Validations
	has_many :parents, through: :reverse_relationships, source: :parent
	has_many :children, through: :relationships, source: :child
	has_many :relationships, foreign_key: "parent_id", dependent: :destroy
	has_many :reverse_relationships, foreign_key: "child_id", class_name: Relationship, dependent: :destroy
	has_many :spouses, through: :spouse_relationships, source: :spouse
	has_many :spouse_relationships, foreign_key: "member_id", dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :updates, dependent: :destroy
	
	accepts_nested_attributes_for :parents, reject_if: proc { |attributes| attributes['first_name'].blank? && attributes['first_name'].blank? }
	accepts_nested_attributes_for :spouses, reject_if: proc { |attributes| attributes['first_name'].blank? && attributes['first_name'].blank? }
	accepts_nested_attributes_for :children, reject_if: proc { |attributes| attributes['first_name'].blank? && attributes['first_name'].blank? }
	
	attr_accessor :password, :crop_x, :crop_y, :crop_w, :crop_h
	
	before_create :encrypt_password, :nil_or_downcase
	before_create { create_token(:remember_token) }
	before_save :encrypt_password, :nil_or_downcase
	after_create :set_oldest_ancestor, :activate_member, :set_last_checked_updates
	after_update :crop_profile_image

	before_destroy :set_ancestor_for_children, :destroy_spouse_id_of_spouse, :delete_posts_from_member, :delete_comments_from_member
	
	state_machine initial: :inactive do
		state :inactive, value: 0
		state :active, value: 1
	
		event :activate_member do
			transition :inactive => :active
		end
	
		event :inactivate_member do
			transition :active => :inactive
		end
	end

	mount_uploader :image, ImageUploader
	
	validates :first_name, presence: true, length: { maximum: 25 }
	validates :last_name, presence: true, length: { maximum: 25 }
	
	VALID_BIRTHDATE_REGEX = /(18|19|20)\d\d[-.](0[1-9]|1[012])[-.](0[1-9]|[12][0-9]|3[01])/
	
	validate :birthdate_format
	
	def birthdate_format	
		unless VALID_BIRTHDATE_REGEX.match( birthdate.to_s )
			errors.add( :birthdate, "must be in the format yyyy-mm-dd")
		end
	end
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	

	validates :password, length: { minimum: 6 }, if: [ :account?, :inactive?]
	validates :password_confirmation, presence: true, if: [ :account?, :inactive?]
	validates_confirmation_of :password, if: [ :account?, :inactive? ]
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }, if: :account?
	
	def set_last_checked_updates
		self.last_checked_updates = Time.now.to_i/1000
		save
	end
	
	def delete_comments_from_member
		Comment.where( member_id: self.id).each do |comment|
			comment.destroy
		end
	end
	
	def delete_posts_from_member
		Post.where( from_member: self.id).each do |post|
			post.destroy
		end
	end
	
	def can_delete_comment?(comment)
		post = Post.find_by_id(comment.post_id)
		(comment.member_id == self.id || post.member_id == self.id)
	end
	
	def can_delete?(post)
		(post.member_id == self.id || post.from_member == self.id)
	end
	
	def crop_profile_image
		image.recreate_versions! if crop_x.present?
	end
	
	def set_oldest_ancestor
		self.oldest_ancestor = self.id if self.oldest_ancestor.nil?
		save
	end
	
	def set_ancestor_for_children
		if self.has_children?
			self.children.each do |child|
				if child.parents.count == 2
					new_ancestor = child.parents.where.not(id: self.id).first.id
				else new_ancestor = child.id end
				remove_ancestor( child.id, new_ancestor )
			end
		end
	end
	
	def destroy_spouse_id_of_spouse
		if self.has_spouse?
			spouse = self.spouse
			spouse.spouse_id = nil
			spouse.save					
		end
	end
	
	def self.not(member)
		Member.where.not(id: [member] + member.children + member.parents + member.spouses).order('last_name', 'first_name')
	end
	
	def nil_or_downcase
		self.email.blank? ?	self.email = nil : self.email.downcase!
	end
	
	def send_password_reset_email
		create_token( :password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		self.state="inactive"
		save(validate: false)
		MemberMailer.reset_password(self).deliver
	end
	
	def reset_token
		self.password_reset_token = nil
		self.password_reset_sent_at = nil
		save
	end
	
	def account?
		self.full_account
	end
	
	def password_reset?
		!self.password_reset_token.nil?
	end

	def Member.new_token
		SecureRandom.urlsafe_base64
	end

	def Member.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	def spouse
		Member.find_by_id(self.spouse_id)
	end
	
	def has_spouse?
		Member.find_by_id(self.spouse_id).present?
	end
	
	def has_children?
		!self.children.empty?
	end
	
	def has_parents?
		!self.parents.empty?
	end
	
	def parent_or_child_of?(member)
		if self.has_children?
			return true if self.children.include?(member)
		end
		if self.has_parents?
			return true if self.parents.include?(member)
		end
		if self.has_spouse?
			return true if self.spouse == member
		end		
		false
	end
	
	def name
		self.first_name + " " + self.last_name
	end
	
	def descendants
		d=[]
		self.children.each do |child|
			d << child
			if child.has_children?
				d.concat( child.descendants )
			end
		end
		d
	end
	
	def descendants_and_their_spouses
		d=[]
		self.children.each do |child|
			d << child
			if child.spouses.present?
				d.concat( child.spouses)
			end
			if child.has_children?
				d.concat( child.descendants_and_their_spouses )
			end
		end
		d	
	end

	def ancestors(degrees)
		return [] if degrees==0
		a = []
		self.parents.each do |parent|
			a << parent
			if parent.has_parents?
				a.concat( parent.ancestors(degrees-1) )
			end
		end
		a << self
	end
	
	def siblings
		unless self.has_parents?
			return nil
		end
		self.parents.first.children.where.not(id: self.id)
	end
	
	def other_spouses( previous_spouse)
		self.spouses.where.not(id: previous_spouse)
	end
	
	def family_of?(member)
		member.ancestors(6).each do |a|
			return true if self.ancestors(6).include?(a)
		end
		if self.has_spouse?
			self.spouse.ancestors(6).each do |a|
				return true if member.ancestors(6).include?(a)
			end
		end
		if member.has_spouse?
			member.spouse.ancestors(6).each do |a|
				return true if self.ancestors(6).include?(a)
			end
			if self.has_spouse?
				member.spouse.ancestors(6).each do |a|
					return true if self.spouse.ancestors(6).include?(a)
				end
			end
		end
		false
	end

	def descendant_or_spouse_of_descendant?(member)
		member.descendants.each do |descendant|
			if descendant == self
				return true
			elsif descendant.has_spouse?
				if descendant.spouse == self
					return true
				end
			end
		end
		return false
	end
	
	def authenticate(password)
		member = Member.find_by_email(self.email)
		member && 
		member.password_hash? &&
		member.password_hash == BCrypt::Engine.hash_secret(password, member.password_salt) ?
			member
			: nil
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret( password, password_salt)
		end
	end

	private		
		def create_token(column)
			self[column] = Member.encrypt(Member.new_token)
		end		
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	
	before_filter :admin_member, only: :destroy
	before_filter :signed_in_filter, only: [ :index, :show, :edit, :update, :destroy, :crop ]
	before_filter :correct_member, only: :edit
	before_filter :correct_member_update, only: :update
	before_filter :within_family, only: :show	
		
	def index
		@members = Member.all.order('last_name', 'first_name').paginate(page: params[ :page])
	end
	
	def show
		@member = Member.find_by_id(params[ :id])
	end

	def new
		@member = Member.new
		@member.children.new
	end
	
	def create
		@member = Member.new(member_params)

		if @member.save
			if @member.full_account?
				sign_in(@member, :remember_token)
				if params[ :member][ :image].present?
					render :crop
				else
					redirect_to tree_path(@member)
				end
			else
				redirect_to member_path(@member)
			end
		else
			render 'new'
		end
	end
	
	def edit
		@member = Member.find_by_id(params[:id])
	end
	
	def update
		@member = Member.find_by_id(params[:id])
		
		if params[ :commit] == ( 'add child' || 'add parent' || 'add spouse')
			if @member.update_attributes(add_member_params)
				flash[ :success] = "Member added to your tree!"
				redirect_to edit_tree_path( @member)
			else
				render 'tree/edit'
			end
		else
			if @member.update_attributes(member_params)
				if params[ :member][ :image].present?
					respond_to do |format|
						format.js { render 'members/crop' }
						format.html { render 'crop' }
					end
				elsif params[ :member][ :last_checked_updates].present?
					@member.update_attribute( :last_checked_updates, Time.at(params[ :member][ :last_checked_updates].to_i/1000))
					render nothing: true
				elsif params[ :member][ :show_spacebar_hint].present?
					render nothing: true
				else
					flash[ :success] = "Your profile was updated successfully."
					redirect_to member_path(@member), status: 303
				end
			else
				render edit_member_path(@member)
			end
		end
	end
	
	def crop
		@member = Member.find_by_id( params[ :id])
		if @member.image?
			render :crop
		else
			redirect_to member_path(@member)
		end
	end
	
	def destroy
		member_to_delete = Member.find( params[ :id] )
		if current_member?(member_to_delete)
			flash[ :error] = "You cannot delete yourself!"
			redirect_to member_path(member_to_delete)
		else		
			member_to_delete.destroy
			flash[ :success] = "Member destroyed."
			redirect_to members_path
		end
	end
	
	def new_post
		@member = Member.find_by_id( params[ :id])

		respond_to do |format|
			format.js
		end
	end
		
	private
	
		def member_params
			params.require(:member).permit(:first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image, :relationship_type, :relationship_id, :crop_x, :crop_y, :crop_w, :crop_h, :allows_editing, :last_checked_updates, :show_spacebar_hint, children_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image], parents_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image], spouses_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image])
		end
		
		def add_member_params
			params.require(:member).permit( children_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image], parents_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image], spouses_attributes: [ :first_name, :last_name, :birthdate, :email, :password, :password_confirmation, :full_account, :spouse_id, :image, :image_cache, :remove_image])
		end
		
		def correct_member
			member = Member.find( params[ :id])
		
			unless current_member?(member) ||
						(member.parent_or_child_of?(current_member) &&
							!member.full_account?) ||
						current_member.admin?
				redirect_to member_path(current_member), flash: { error: "You do not have permissions to edit or update this member."}
			end
		end
		
		def correct_member_update
			member = Member.find_by_id( params[ :id])
			logger.debug("Commit is #{['add child', 'add parent', 'add spouse'].include?(params[ :commit])}")

			if current_member?(member)
				return
			end

			if ['add child', 'add parent', 'add spouse'].include?(params[ :commit])
				unless member.allows_editing
					redirect_to member_path( current_member), flash: { error: "This member does not allow other members to edit their tree."}
				end
				
				unless current_member.family_of?(member)
					redirect_to member_path( current_member), flash: { error: "You do not have permissions to edit or update this member."}
				end
			elsif params[ :commit] == 'update my profile'
				unless ( !member.full_account && current_member.parent_or_child_of?(member) )
					redirect_to member_path( current_member), flash: { error: "You do not have permissions to edit or update this member."}
				end
			else redirect_to root_path, flash: { error: "We don't know what you're trying to do, so we've sent you here." }
			end
		end
		
end

app/helpers/members_helper.rb
module MembersHelper
    include ActionView::Helpers::TextHelper
    include ActionView::Helpers::UrlHelper
    include ActionView::Helpers::AssetTagHelper

	def build_tree(add_member, oldest_ancestor_id)
		children = []
		id = add_member.birthdate.to_time.to_i + rand(1000000)

		name = "<div class='tree_image_block'>#{ image_tag( add_member.image_url( :small), class: 'img-rounded tree_image') }"
		if add_member.has_spouse?
			name += "#{ image_tag( add_member.spouse.image_url( :small), class: 'img-rounded tree_image') }"
		end
		# add link to switch to member's other divorced parent's tree
		if add_member.parents.count==2 && !(add_member.parents.first.spouse == add_member.parents.last)
			if add_member.parents.first.oldest_ancestor == oldest_ancestor_id
				oldest_ancestor = add_member.parents.last.oldest_ancestor
			else
				oldest_ancestor = add_member.parents.first.oldest_ancestor
			end
			name += "<div class='over_image btm extend'><span class='member_name_in_tree'>#{ link_to( add_member.first_name, tree_path(oldest_ancestor) ) }"
		else
			name += "<div class='over_image btm extend'><span class='member_name_in_tree'>#{add_member.first_name}"
		end
		
		# add link to switch to member's spouse's tree, if any
		if add_member.has_spouse?
			link = link_to(add_member.spouse.first_name, tree_path(add_member.spouse) )
			name += " and " + link + " " + add_member.last_name
			# add link to edit member's and spouse's tree
			edit =
			"</span><div class='edit'>
				edit #{ link_to "#{add_member.first_name}'s", edit_tree_path(add_member) } or #{ link_to "#{add_member.spouse.first_name}'s ", edit_tree_path(add_member.spouse) } tree<br/>
				view #{ link_to "#{add_member.first_name}'s", member_path(add_member) } or 	#{ link_to "#{add_member.spouse.first_name}'s", member_path(add_member.spouse) }	profile
			</div></div></div>"
		else
			name += " " + add_member.last_name
			# add link to edit member's tree
			edit = 
			"</span><div class='edit'>
				edit #{ link_to "#{add_member.first_name}'s", edit_tree_path(add_member) }	 tree<br/>
				view #{ link_to "#{add_member.first_name}'s", member_path(add_member) } profile
			</div></div></div>"
		end
		
		name += edit
		
		if (add_member.has_children? || (add_member.has_spouse? && add_member.spouse.has_children?))
			Member.where(id: Relationship.select('child_id').where(parent_id: [add_member, add_member.spouse_id])).order('birthdate').each do |child|
				children << build_tree(child, oldest_ancestor_id)
			end
		end
		
		return {"id" => id, "name" => name, "children" => children}
	end

	# set oldest_ancestor of member old and all of their descendants to value new
	def remove_ancestor( old, new)
		member = Member.find_by_id(old)
		member.oldest_ancestor = new
		member.save
		unless member.children.nil?
			member.descendants.each do |d|
				d.oldest_ancestor = new
				d.save
			end
		end
	end
	
	def add(spouses)
		new_spouses=[]
		spouses.each do |spouse|
			new_spouses << spouse
			new_spouses.concat( spouse.descendants_and_their_spouses)
		end
		new_spouses
	end
	
end

app/views/members/_child_select_form.html.erb
<%= form_for( member.relationships.new(parent_id: member.id), html: { class: 'f-hz' } ) do |f| %>

<%= f.hidden_field :parent_id %>
<%= collection_select( :relationship, :child_id, Member.not(member), :id, :name, { prompt: "add a child from the current family members"}, { class: "member_select" }) %>

<%= f.submit "add child", class: "btn btn-sm btn-primary btn-hz" %>

<% end %>

app/views/members/_hidden_profile_image_upload.html.erb
<%= form_for @member, html: { id: 'hidden_profile_image', class: 'file-upload hide' } do |f| %>
	<%= f.file_field :image, id: "hidden_profile_image_upload_field" %>
<% end %>

app/views/members/_image_upload.html.erb
<%= form_for @member.images.new do |f| %>
	<%= f.label :image, "Drag and drop your images, or choose files below." %>
	<%= f.file_field :image, multiple: true, name: "image[image]" %>
	<%= f.hidden_field :member_id, value: current_member.id %>
	<%= f.submit "upload my images", class: "btn btn-lg btn-primary", id: 'image_upload_submit', disabled: true %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
	{%=o.name%}
	<div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/members/_member.html.erb
<% unless member.new_record? %>
<li>
	<%= image_tag( member.image_url(:thumb)) %>
	<div>
	<%= link_to full_name(member.first_name, member.last_name), member %> <br/>
	<%= link_to "edit #{member.first_name}'s tree", edit_tree_path(member) %>
	<% if !member.full_account? && current_member.parent_or_child_of?(member)%>
		| <%= link_to "edit #{member.first_name}'s profile", edit_member_path(member) %>
	<% end %>
	
	<% if params[ :controller] == 'tree' %>

		<% if member.children.include?(@member) %>
		| <%= link_to "remove parent", relationship_path( member.relationships.find_by_child_id(@member.id), member: { id: @member.id }), method: :delete %>
		<% end %>
		<% if @member.spouse == member %>
		| <%= link_to "remove spouse", spouse_relationship_path( @member.spouse_relationships.find_by_spouse_id( member.id ) ), method: :delete %>
		<% end %>
		<% if member.parents.include?(@member) %>
		| <%= link_to "remove child", relationship_path( @member.relationships.find_by_child_id(member.id), member: { id: @member.id }) , method: :delete %>
		<% end %>
	<% end %>
	
	<% if current_member.admin? && !current_member?(member) %>
		| <%= link_to "delete member", member, method: :delete, confirm: "Are you sure?" %>
	<% end %>
	</div>
</li>
<% end %>

app/views/members/_new_member_form.html.erb
<div class="row">
	<div class="col-lg-6 col-lg-offset-3">
		<%= form_for(@member, html: { class: 'f-vt'}) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :first_name %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name %>
		<%= f.text_field :last_name %>

		<%= f.label :birthdate %>
		<%= f.text_field :birthdate, placeholder: "YYYY-MM-DD, e.g. May 1st, 2013 is 2013-05-01" %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirm Password" %>
		<%= f.password_field :password_confirmation %>
	
		<%= f.hidden_field :full_account, value: 'true' %>
	
		<%= f.submit "sign me up!", class: "btn btn-primary btn-vt" %>
	<% end %>
	</div>
</div>

app/views/members/_parent_member_form.html.erb
<%= form_for @member, method: :patch, html: { class: 'f-vt', autocomplete: 'off' } do |f| %>
	
	<%= f.fields_for :parents, @member.parents.new do |rel| %>

	<% end %>
	<p><%= link_to_add_fields( "add a new member as a parent", f, :parents, :relationship, name: 'parent' ) %></p>
	
	<%= f.submit "add parent", class: "btn btn-primary btn-vt add_member" %>
<% end %>

app/views/members/_relationship_fields.html.erb
<div class="row relationship_fields">
	<div class="col-lg-4">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name %>
		<%= f.text_field :last_name %>

		<%= f.label :birthdate %>
		<%= f.text_field :birthdate, placeholder: "YYYY-MM-DD, e.g. May 1st, 2013 is 2013-05-01" %>
	</div>
		
	<div class="col-lg-4">
		<%= f.check_box :full_account, onclick:"showFullForm(this)" %>
		<%= f.label :full_account, "I want to provide this member with a full account that allows them to add and update other members and member information." %><br/>

		<%= link_to_remove_fields "nevermind, i don't want to add a new #{name}", f %>
	</div>

	<div id="full_member_field">
			<div class="col-lg-4">
				<%= f.label :email %>
				<%= f.text_field :email, autocomplete: :off, value: '' %>

				<%= f.label :password %>
				<%= f.password_field :password, autocomplete: :off, value: '' %>

				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation %>
			</div>
	</div>
</div>

app/views/members/_spouse_relationship_fields.html.erb
<div class="row">
	<div class="col-lg-4">
		<h3>add a new <%= name.to_s %></h3>

		<%= f.label :first_name %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name %>
		<%= f.text_field :last_name %>

		<%= f.label :birthdate %>
		<%= f.text_field :birthdate, placeholder: "YYYY-MM-DD, e.g. May 1st, 2013 is 2013-05-01" %>
	</div>
	
	<div class="col-lg-4">
		<%= f.check_box :full_account, class: "check_box_label", onclick:"showFullForm(this)" %>
		<%= f.label :full_account, "I want to provide this member with a full account that allows them to add and update other members and member information." %>

	</div>
	
	<div class="col-lg-4">
		<div id="full_member_field">
		<%= f.label :email %>
		<%= f.text_field :email, autocomplete: :off, value: "" %>

		<%= f.label :password %>
		<%= f.password_field :password, autocomplete: :off, value: "" %>

		<%= f.label :password_confirmation, "Confirm Password" %>
		<%= f.password_field :password_confirmation %>
		</div>
	</div>
	
	<%= f.hidden_field :spouse_id, value: @member.id %>

	<%= link_to_remove_fields "don't add a new #{name}", f %>
	</div>
</div>

app/views/members/_update_member_form.html.erb
<%= form_for(@member, html: { class: 'f-vt'}) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

<div class="row">
<div class="col-lg-4">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>

	<%= f.label :birthdate %>
	<%= f.text_field :birthdate, placeholder: "YYYY-MM-DD, e.g. May 1st, 2013 is 2013-05-01" %>
</div>

<div class="col-lg-4">
	<%= f.label :email %>
	<%= f.text_field :email %>

	<br/>
	<%= link_to "Change my password", change_password_password_reset_path(@member) %>
</div>

<div class="col-lg-4">	
	<%= image_tag(@member.image_url(:thumb)) if @member.image? %>
	<%= f.label :image, "Upload a new profile picture" %>
	<%= f.file_field :image %>
	<%= f.hidden_field :image_cache %>

	<%= f.check_box :remove_image %>
	<%= f.label :remove_image, "Remove image" %>

</div></div>
	<%= f.submit "update my profile", class: "btn btn-primary btn-vt" %>
<% end %>

app/views/members/crop.js.erb
$('#profile_image_holder').fadeOut('slow', function() { 
	$('#profile_image').remove()
	$('#profile_image_holder').css('display', 'none')
	$('#profile_image_holder').prepend(" <%= j render partial: 'member_profile_image', object: @member, as: :member %>")
	$('#profile_image_holder').fadeIn(1000)
})

app/views/members/edit.html.erb
<% provide(:title, "Edit profile") %>
<h1>Edit profile</h1>

<div class="fields">
	<div class="">
		<%= render partial: 'update_member_form' , locals: { action: 'update' } %>
	</div>
</div>

app/views/members/index.html.erb
<% provide(:title, "Who's who".html_safe) %>
<h1>Who's who</h1>

<ul class="members">
	<%= render @members %>
</ul>

<%= will_paginate %>

app/views/members/new.html.erb
<% provide(:title, "add member") %>
<h1>sign up!</h1>

<div class="fields">
	<div class="">
		<%= render 'new_member_form' %>
	</div>
</div>

app/views/members/new_post.html.erb
<%= render partial: 'posts/post_form' %>